/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraficalUserInterface;

import FleetModel.FleetModelPKW;
import java.awt.CardLayout;
import Data.LKW;
import Data.PKW;
import Database.DB_Access;
import FleetModel.FleetModelLKW;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author fabianzach
 */
public class FleetGUI extends javax.swing.JFrame
{

  private FleetModelPKW fmp = new FleetModelPKW();
  private FleetModelLKW fml = new FleetModelLKW();
  private DB_Access db = DB_Access.getInstance();

  public FleetGUI()
  {
    initComponents();
    jtPKW.setModel(fmp);
    jtLKW.setModel(fml);
    JOptionPane.showMessageDialog(this, "Please make sure that your Database is Running before you add your Data");

    try
    {
      fml.initLKWList();
      fmp.initPKWList();
    }
    catch (SQLException ex)
    {
      Logger.getLogger(FleetGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    buttonGroup1 = new javax.swing.ButtonGroup();
    jPanel3 = new javax.swing.JPanel();
    jPanel5 = new javax.swing.JPanel();
    rbPKW = new javax.swing.JRadioButton();
    rbLKW = new javax.swing.JRadioButton();
    jPanel4 = new javax.swing.JPanel();
    Clear = new javax.swing.JButton();
    paListParent = new javax.swing.JPanel();
    paPKWL = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    jtPKW = new javax.swing.JTable();
    paLKWL = new javax.swing.JPanel();
    jScrollPane3 = new javax.swing.JScrollPane();
    jtLKW = new javax.swing.JTable();
    paParent = new javax.swing.JPanel();
    paPKW = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    tfID = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    tfBrand = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    tfSpez = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jLabel2 = new javax.swing.JLabel();
    tfWeight = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    tfSeats = new javax.swing.JTextField();
    jLabel5 = new javax.swing.JLabel();
    tfHorsepower = new javax.swing.JTextField();
    jLabel14 = new javax.swing.JLabel();
    paLKW = new javax.swing.JPanel();
    jLabel8 = new javax.swing.JLabel();
    tfIDLkw = new javax.swing.JTextField();
    jLabel11 = new javax.swing.JLabel();
    tfBrandLkw = new javax.swing.JTextField();
    jLabel10 = new javax.swing.JLabel();
    tfHPLKW = new javax.swing.JTextField();
    jButton4 = new javax.swing.JButton();
    jLabel9 = new javax.swing.JLabel();
    tfWeightLKW = new javax.swing.JTextField();
    jLabel12 = new javax.swing.JLabel();
    tfAxes = new javax.swing.JTextField();
    jLabel13 = new javax.swing.JLabel();
    tfKilo = new javax.swing.JTextField();
    jLabel15 = new javax.swing.JLabel();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    jMenuItem2 = new javax.swing.JMenuItem();
    jMenuItem3 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel3.setLayout(new java.awt.BorderLayout());

    jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter"));
    jPanel5.setLayout(new java.awt.GridLayout(1, 2));

    buttonGroup1.add(rbPKW);
    rbPKW.setSelected(true);
    rbPKW.setText("PKW");
    rbPKW.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onFilterPKW(evt);
      }
    });
    jPanel5.add(rbPKW);

    buttonGroup1.add(rbLKW);
    rbLKW.setText("LKW");
    rbLKW.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onFilterLKW(evt);
      }
    });
    jPanel5.add(rbLKW);

    jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

    jPanel4.setLayout(new java.awt.GridLayout(1, 3));

    Clear.setText("Clear");
    Clear.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onClear(evt);
      }
    });
    jPanel4.add(Clear);

    jPanel3.add(jPanel4, java.awt.BorderLayout.WEST);

    getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

    paListParent.setLayout(new java.awt.CardLayout());

    paPKWL.setLayout(new java.awt.GridLayout(1, 0));

    jtPKW.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String []
      {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane2.setViewportView(jtPKW);

    paPKWL.add(jScrollPane2);

    paListParent.add(paPKWL, "card3");

    paLKWL.setLayout(new java.awt.GridLayout(1, 0));

    jtLKW.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String []
      {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jScrollPane3.setViewportView(jtLKW);

    paLKWL.add(jScrollPane3);

    paListParent.add(paLKWL, "card2");

    getContentPane().add(paListParent, java.awt.BorderLayout.CENTER);

    paParent.setLayout(new java.awt.CardLayout());

    paPKW.setLayout(new java.awt.GridLayout(2, 7));

    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("ID");
    paPKW.add(jLabel1);

    tfID.setText("1");
    paPKW.add(tfID);

    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("Brand");
    paPKW.add(jLabel3);

    tfBrand.setText("BMW");
    paPKW.add(tfBrand);

    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel6.setText("Spezification");
    paPKW.add(jLabel6);

    tfSpez.setText("X1");
    paPKW.add(tfSpez);

    jButton1.setText("Add");
    jButton1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onAddPKW(evt);
      }
    });
    paPKW.add(jButton1);

    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("Weight");
    paPKW.add(jLabel2);

    tfWeight.setText("1500");
    paPKW.add(tfWeight);

    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel4.setText("Seats");
    paPKW.add(jLabel4);

    tfSeats.setText("5");
    paPKW.add(tfSeats);

    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("HorsePower");
    paPKW.add(jLabel5);

    tfHorsepower.setText("225");
    paPKW.add(tfHorsepower);
    paPKW.add(jLabel14);

    paParent.add(paPKW, "cardPKW");

    paLKW.setEnabled(false);
    paLKW.setLayout(new java.awt.GridLayout(2, 7));

    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel8.setText("ID");
    jLabel8.setToolTipText("");
    paLKW.add(jLabel8);

    tfIDLkw.setText("1");
    tfIDLkw.setToolTipText("");
    paLKW.add(tfIDLkw);

    jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel11.setText("Brand");
    paLKW.add(jLabel11);

    tfBrandLkw.setText("Man");
    paLKW.add(tfBrandLkw);

    jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel10.setText("Horsepower");
    paLKW.add(jLabel10);

    tfHPLKW.setText("750");
    paLKW.add(tfHPLKW);

    jButton4.setText("Add");
    jButton4.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onAddLKW(evt);
      }
    });
    paLKW.add(jButton4);

    jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel9.setText("Weight");
    paLKW.add(jLabel9);

    tfWeightLKW.setText("4500");
    paLKW.add(tfWeightLKW);

    jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel12.setText("Axes");
    paLKW.add(jLabel12);

    tfAxes.setText("3");
    paLKW.add(tfAxes);

    jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel13.setText("Kilometers");
    paLKW.add(jLabel13);

    tfKilo.setText("172000");
    paLKW.add(tfKilo);
    paLKW.add(jLabel15);

    paParent.add(paLKW, "cardLKW");

    getContentPane().add(paParent, java.awt.BorderLayout.PAGE_END);

    jMenu1.setText("File");
    jMenu1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onLoad(evt);
      }
    });

    jMenuItem1.setText("add Tables");
    jMenuItem1.setToolTipText("");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onAddTables(evt);
      }
    });
    jMenu1.add(jMenuItem1);

    jMenuItem2.setText("save Data in Serzializedfile");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onSaveData(evt);
      }
    });
    jMenu1.add(jMenuItem2);

    jMenuItem3.setText("loadData");
    jMenu1.add(jMenuItem3);

    jMenuBar1.add(jMenu1);

    setJMenuBar(jMenuBar1);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void onFilterPKW(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onFilterPKW
  {//GEN-HEADEREND:event_onFilterPKW
    CardLayout layout = (CardLayout) paParent.getLayout();
    layout.show(paParent, "cardPKW");

    CardLayout l = (CardLayout) paListParent.getLayout();
    l.show(paListParent, "card3");
  }//GEN-LAST:event_onFilterPKW

  private void onFilterLKW(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onFilterLKW
  {//GEN-HEADEREND:event_onFilterLKW
    CardLayout layout = (CardLayout) paParent.getLayout();
    layout.show(paParent, "cardLKW");

    CardLayout l = (CardLayout) paListParent.getLayout();
    l.show(paListParent, "card2");
    repaint();
  }//GEN-LAST:event_onFilterLKW

  private void onAddLKW(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onAddLKW
  {//GEN-HEADEREND:event_onAddLKW
    int id = Integer.parseInt(tfIDLkw.getText());
    String brand = tfBrandLkw.getText();
    int axes = Integer.parseInt(tfAxes.getText());
    int hp = Integer.parseInt(tfHPLKW.getText());
    int kilometers = Integer.parseInt(tfKilo.getText());
    int weight = Integer.parseInt(tfWeightLKW.getText());

    try
    {
      fml.addLKW(new LKW(id, brand, axes, weight, kilometers, hp));
    }
    catch (SQLException ex)
    {
      Logger.getLogger(FleetGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_onAddLKW

  private void onAddPKW(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onAddPKW
  {//GEN-HEADEREND:event_onAddPKW
    int id = Integer.parseInt(tfID.getText());
    String brand = tfBrand.getText();
    String spez = tfSpez.getText();
    int hp = Integer.parseInt(tfHorsepower.getText());
    int seats = Integer.parseInt(tfSeats.getText());
    int weight = Integer.parseInt(tfWeight.getText());
    System.out.println("" + id + brand + spez + hp + seats + weight);

    try
    {
      fmp.addPKW(new PKW(id, brand, seats, spez, hp, weight));
    }
    catch (SQLException ex)
    {
      Logger.getLogger(FleetGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_onAddPKW

  private void onAddTables(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onAddTables
  {//GEN-HEADEREND:event_onAddTables
    try
    {
      db.addTables();
    }
    catch (SQLException ex)
    {
      Logger.getLogger(FleetGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_onAddTables

  private void onSaveData(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onSaveData
  {//GEN-HEADEREND:event_onSaveData
    try
    {
      fmp.savePKW();
      fml.saveLKW();
    }
    catch (IOException ex)
    {
      Logger.getLogger(FleetGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_onSaveData

  private void onClear(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onClear
  {//GEN-HEADEREND:event_onClear

  }//GEN-LAST:event_onClear

  private void onLoad(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onLoad
  {//GEN-HEADEREND:event_onLoad
    try
    {
      fmp.loadPKW();
      fml.loadLKW();

      JOptionPane.showMessageDialog(this, "Please make sure you have the right synchronization with the Database");
    }
    catch (IOException ex)
    {
      Logger.getLogger(FleetGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
    catch (ClassNotFoundException ex)
    {
      Logger.getLogger(FleetGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_onLoad

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(FleetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(FleetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(FleetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(FleetGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new FleetGUI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Clear;
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton4;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel13;
  private javax.swing.JLabel jLabel14;
  private javax.swing.JLabel jLabel15;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JMenuItem jMenuItem3;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JTable jtLKW;
  private javax.swing.JTable jtPKW;
  private javax.swing.JPanel paLKW;
  private javax.swing.JPanel paLKWL;
  private javax.swing.JPanel paListParent;
  private javax.swing.JPanel paPKW;
  private javax.swing.JPanel paPKWL;
  private javax.swing.JPanel paParent;
  private javax.swing.JRadioButton rbLKW;
  private javax.swing.JRadioButton rbPKW;
  private javax.swing.JTextField tfAxes;
  private javax.swing.JTextField tfBrand;
  private javax.swing.JTextField tfBrandLkw;
  private javax.swing.JTextField tfHPLKW;
  private javax.swing.JTextField tfHorsepower;
  private javax.swing.JTextField tfID;
  private javax.swing.JTextField tfIDLkw;
  private javax.swing.JTextField tfKilo;
  private javax.swing.JTextField tfSeats;
  private javax.swing.JTextField tfSpez;
  private javax.swing.JTextField tfWeight;
  private javax.swing.JTextField tfWeightLKW;
  // End of variables declaration//GEN-END:variables

}
